# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'quanty'

#google-ID: 'UA-112060364-1'

menu:
- {name: 'about', path: 'menu', url: 'about.html'}
- {name: 'archive', path: 'menu', url: 'writing.html'}
- {name: 'contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/gem763'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'facebook', link: 'https://facebook.com/sejin.kang.777'}
- {icon: 'envelope', link: 'mailto:gem763@hanmail.net'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
